Update action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,2 +1,25 @@
 name: Release-FHIR-Package-To-Registry (GitHub Actions)
 description: Release a FHIR Package to a package regsitry as part of a GitHub Actions pipeline
+
+runs:
+  using: "composite"
+  steps:
+  
+    # --------------------------------------------------------------------------------------------------- #
+    #                                GENERATE PACKAGE USING FIRELY TERMINAL                               #
+    # --------------------------------------------------------------------------------------------------- #
+  
+    # Firely.Terminal steps
+    
+    - name: Check if .NET is installed
+      run: |
+        if $INPUT_DOTNET_VALIDATION_ENABLED; then
+          if ! command -v dotnet &> /dev/null
+          then
+              echo "dotnet could not be found. Please see actions/setup-dotnet to set it up before running this action."
+              exit 1
+          fi
+        fi
+      shell: bash
+      env:
+        INPUT_DOTNET_VALIDATION_ENABLED: ${{ inputs.DOTNET_VALIDATION_ENABLED }}
