Update action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -8,18 +8,43 @@ runs:
     # --------------------------------------------------------------------------------------------------- #
     #                                GENERATE PACKAGE USING FIRELY TERMINAL                               #
     # --------------------------------------------------------------------------------------------------- #
-  
-    # Firely.Terminal steps
     
     - name: Check if .NET is installed
       run: |
-        if $INPUT_DOTNET_VALIDATION_ENABLED; then
-          if ! command -v dotnet &> /dev/null
+        if ! command -v dotnet &> /dev/null
           then
-              echo "dotnet could not be found. Please see actions/setup-dotnet to set it up before running this action."
-              exit 1
-          fi
+            echo "dotnet could not be found. Please see actions/setup-dotnet to set it up before running this action."
+            exit 1
         fi
       shell: bash
+      
+    # Test .NET SDK version
+    - name: Check .NET SDK Version
+      run: |
+        CHECK_DOTNET_VERSION=$(dotnet --version)
+        echo "DOTNET_VERSION: $CHECK_DOTNET_VERSION"
+      shell: bash
+      
+    # Install Firely.Terminal
+    - name: Install Firely.Terminal
+      run: |
+        dotnet tool install --global Firely.Terminal --version $FIRELY_TERMINAL_VERSION > /dev/null
+      shell: bash
       env:
-        INPUT_DOTNET_VALIDATION_ENABLED: ${{ inputs.DOTNET_VALIDATION_ENABLED }}
+       FIRELY_TERMINAL_VERSION: 2.5.0-beta-7
+       
+    # Test Firely.Terminal install
+    - name: Check Firely Terminal Version
+      run: |
+        CHECK_FIRELY_TERMINAL_VERSION=$(fhir -v | tr '\n' ' ') # Print everything in a single line
+        echo "FIRELY_TERMINAL_VERSION: $CHECK_FIRELY_TERMINAL_VERSION"
+      shell: bash
+      
+    # Simplifier Login
+    - name: Simplifier login
+      run: |
+        fhir login email=$INPUT_SIMPLIFIER_USERNAME password=$INPUT_SIMPLIFIER_PASSWORD
+      shell: bash
+      env:
+       INPUT_SIMPLIFIER_USERNAME: ${{ inputs.SIMPLIFIER_USERNAME }}
+       INPUT_SIMPLIFIER_PASSWORD: ${{ inputs.SIMPLIFIER_PASSWORD }}
